update/delete database
PSUCompBio/compbio pull request #62
Opened 2017-07-31 05:06 UTC by rushali30

2017-07-31 05:10 UTC, rushali30 commented
Update/delete functions

2017-07-31 05:11 UTC, srikumar947 commented on src/csps/src/coachsafeplaysafe.py
> +mnnno_sensor_api = False
mnno_sensor? Have you modified screen two code?

2017-07-31 05:11 UTC, srikumar947 requested changes
Why are you committing pyc (compiled python) and db files?

2017-08-02 13:17 UTC, rhk12 commented
@srikumar947 you might need to make the changes.I am not sure if Rushali will do it.

2017-08-02 13:37 UTC, closed without merging